#!/usr/bin/env python3
"""Extract the SDK's plain-C matrix / vector / quaternion functions for the port.

src/lib/mtx.c, mtx44.c, mtxvec.c, quat.c and vec.c hold each function twice: a C_ version and a
paired-single asm version (PS*), the latter in CodeWarrior asm syntax no other compiler reads.
This writes the C_ versions the game needs into one C file; port/src/port_mtx.cpp binds the PS*
names to them.

    python3 tools/port/extract_sdk_c.py build/port/sdk_mtx.c
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WANT = [
    "C_MTXIdentity", "C_MTXCopy", "C_MTXConcat", "C_MTXInverse", "C_MTXRotTrig", "C_MTXMultVec", "C_MTXMultVecArray",
    "C_MTXMultVecSR", "C_MTXQuat", "C_MTXRotAxisRad", "C_MTXRotRad", "C_MTXScale", "C_MTXTrans",
    "C_MTXTransApply", "C_MTXTranspose", "C_MTX44MultVec", "C_MTXFrustum", "C_MTXLightPerspective",
    "C_MTXLookAt", "C_MTXOrtho", "C_MTXPerspective", "C_VECAdd", "C_VECSubtract", "C_VECScale",
    "C_VECNormalize", "C_VECDotProduct", "C_VECCrossProduct", "C_VECMag", "C_VECSquareMag",
    "C_VECDistance", "C_VECSquareDistance", "C_VECReflect", "C_QUATMtx", "C_QUATSlerp",
    "C_QUATMultiply", "C_QUATNormalize", "C_QUATDotProduct", "C_QUATScale", "C_QUATAdd",
]


def main(out: Path):
    parts = ['// Generated by tools/port/extract_sdk_c.py from src/lib/{mtx,mtx44,mtxvec,mtx44vec,quat,vec}.c.',
             '#include "types.h"', '#include <math.h>', '#include <dolphin/mtx.h>',
             '#define ASSERTMSGLINE(line, cond, msg) ((void) 0)', '']
    found = set()
    for name in ("mtx", "mtx44", "mtxvec", "mtx44vec", "quat", "vec"):
        t = (ROOT / "src" / "lib" / f"{name}.c").read_text(errors="replace")
        for fn in WANT:
            m = re.search(r"(?m)^[A-Za-z0-9_ \*]*\b" + fn + r"\s*\([^)]*\)\s*\{", t)
            if not m or fn in found:
                continue
            j = t.index("\n}\n", m.start()) + 3
            parts.append(f"// ---- {name}.c\n" + t[m.start():j])
            found.add(fn)
    missing = [fn for fn in WANT if fn not in found]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts) + "\n")
    print(f"{len(found)} functions -> {out}" + (f"; missing: {missing}" if missing else ""))


if __name__ == "__main__":
    main(Path(sys.argv[1]))
