#!/usr/bin/env python3
"""Emit the port build's unit list from the matching build's configuration.

Reads config/G4BE08/objects.py (DOL units) and modules.py (REL units) and writes a CMake fragment:

    RE4_DOL_UNITS        game sources linked into the DOL (relative to src/)
    RE4_MODULES          the REL module names
    RE4_MODULE_<mod>     that module's sources (relative to src/)

Dropped: everything under src/lib (Nintendo SDK, CRI, SN runtime, libgcc: replaced by the
port's platform layer and the PSP toolchain), the newlib C units in src/game (*.c: the PSP libc
provides them), and src/game/memset_2.cpp / yz2asm.cpp (PowerPC asm bodies, reimplemented in
port/src). A module tuple's third element names a source shared by several modules
(e.g. wep/pl_handgun.cpp); the same source is then listed under each module.

    python3 tools/port/units.py build/port/units.cmake
"""
import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONFIG = ROOT / "config" / "G4BE08"
ASM_BODIED = {"game/memset_2.cpp", "game/yz2asm.cpp"}


def load(name):
    spec = importlib.util.spec_from_file_location(name, CONFIG / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def keep(unit: str) -> bool:
    if unit.startswith("lib/"):
        return False
    if unit.endswith(".c"):
        return False
    if unit in ASM_BODIED:
        return False
    return True


def module_source(entry) -> str:
    unit = entry[0]
    if len(entry) > 2 and entry[2]:
        return entry[2]
    return unit


def main(out: Path):
    objects = load("objects")
    modules = load("modules")
    dol = [u for u in objects.UNITS if keep(u)]
    lines = ["# Generated by tools/port/units.py from config/G4BE08/{objects,modules}.py. Do not edit.", ""]
    lines.append("set(RE4_DOL_UNITS")
    lines += [f"  {u}" for u in dol]
    lines.append(")")
    lines.append("")
    # Every module with REL data (config/G4BE08/modules/<name>/); modules.py lists the unit
    # boundaries only where a module is more than its own <name>/<name>.cpp.
    names = sorted(p.name for p in (CONFIG / "modules").iterdir() if (p / "rel.json").exists())
    lines.append("set(RE4_MODULES " + " ".join(names) + ")")
    for name in names:
        srcs = []
        for entry in modules.UNITS.get(name, [(f"{name}/{name}.cpp", None)]):
            s = module_source(entry)
            if keep(s) and s not in srcs:
                srcs.append(s)
        lines.append(f"set(RE4_MODULE_{name}")
        lines += [f"  {s}" for s in srcs]
        lines.append(")")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    n_mod = sum(len(modules.UNITS.get(m, [0])) for m in names)
    print(f"{len(dol)} DOL units, {len(names)} modules ({n_mod} module units) -> {out}")


if __name__ == "__main__":
    main(Path(sys.argv[1] if len(sys.argv) > 1 else ROOT / "build" / "port" / "units.cmake"))
